[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = '''
    default-src 'none';
    font-src 'self';
    img-src https: data: blob:;
    media-src https: data: blob:;
    base-uri 'none';
    script-src 'self' eyesight.eilu.me;
    style-src 'self';
    manifest-src 'self';
    connect-src 'self' eyesight.eilu.me;
    object-src 'none';
    frame-src 'self' www.youtube-nocookie.com;
    frame-ancestors https://www.youtube-nocookie.com;
    form-action 'self';
    upgrade-insecure-requests;
    '''
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "no-referrer, strict-origin-when-cross-origin"